image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - terraform --version
  - terraform init

stages:
  - Validation
  - Formatting
  - Acceptance

validate:
  stage: Validation
  script:
    - terraform validate

fmt:
  stage: Formatting
  script:
    - echo "Hello world"
  dependencies:
    - validate

tflint:
  stage: Acceptance
  script:
    - echo "Hello world"
  dependencies:
    - fmt